import React, { useState, useEffect } from 'react';
import { View, Text, TouchableOpacity, ScrollView, StyleSheet, ActivityIndicator, TextInput } from 'react-native';
import { C, fonts, TILE_BG } from '../theme';
import { GroceryItem, Recipe } from '../types';
import { saveApiKey } from '../storage';

type FilterKey = 'expiring' | 'quick' | 'protein' | null;

const FILTERS: { key: FilterKey; label: string }[] = [
  { key: 'expiring', label: 'Uses expiring' },
  { key: 'quick', label: 'Quick · under 20m' },
  { key: 'protein', label: 'High protein' },
];

function leadingNumber(s: string): number {
  const m = (s || '').match(/\d+/);
  return m ? parseInt(m[0], 10) : 0;
}

export default function RecipesScreen({
  items,
  recipes,
  loading,
  error,
  onGenerate,
  onOpenRecipe,
  apiKey,
  onApiKeyChange,
}: {
  items: GroceryItem[];
  recipes: Recipe[];
  loading: boolean;
  error: string | null;
  onGenerate: () => void;
  onOpenRecipe: (r: Recipe) => void;
  apiKey: string;
  onApiKeyChange: (key: string) => void;
}) {
  const [filter, setFilter] = useState<FilterKey>(null);
  const [localKey, setLocalKey] = useState(apiKey);

  // Auto-generate on first arrival once we have a key and a non-empty pantry.
  useEffect(() => {
    if (apiKey && items.length > 0 && recipes.length === 0 && !loading && !error) {
      onGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [apiKey, items.length, recipes.length, loading, error]);

  const Header = ({ showRefresh }: { showRefresh?: boolean }) => (
    <View style={styles.headerRow}>
      <View style={{ flex: 1 }}>
        <Text style={styles.heading}>Cook with what you have</Text>
        <Text style={styles.subtitle}>AI recipe ideas from your pantry — soon-to-expire items first.</Text>
      </View>
      {showRefresh && (
        <TouchableOpacity onPress={onGenerate} disabled={loading} style={styles.refreshBtn} activeOpacity={0.8}>
          <Text style={styles.refreshIcon}>↻</Text>
        </TouchableOpacity>
      )}
    </View>
  );

  // 1) No API key yet.
  if (!apiKey) {
    return (
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
        <Header />
        <View style={styles.apiCard}>
          <Text style={styles.apiLabel}>🔑 Gemini API key</Text>
          <Text style={styles.apiHint}>Recipe ideas are generated by Google Gemini from your pantry. Add your key to enable them.</Text>
          <TextInput
            value={localKey}
            onChangeText={setLocalKey}
            placeholder="AIza..."
            placeholderTextColor="#9AA290"
            style={styles.apiInput}
            secureTextEntry
            autoCapitalize="none"
          />
          <TouchableOpacity
            onPress={async () => { const k = localKey.trim(); await saveApiKey(k); onApiKeyChange(k); }}
            style={styles.apiSaveBtn}
            activeOpacity={0.85}
          >
            <Text style={styles.apiSaveText}>Save key</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    );
  }

  // 2) Empty pantry.
  if (items.length === 0) {
    return (
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <Header />
        <View style={styles.centerBox}>
          <Text style={styles.centerEmoji}>🍳</Text>
          <Text style={styles.centerTitle}>Add items to get recipes</Text>
          <Text style={styles.centerSub}>Once your pantry has a few ingredients, we'll suggest recipes you can make with them.</Text>
        </View>
      </ScrollView>
    );
  }

  // 3) Loading (with nothing to show yet).
  if (loading && recipes.length === 0) {
    return (
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <Header />
        <View style={styles.centerBox}>
          <ActivityIndicator size="large" color={C.green} />
          <Text style={styles.centerSub}>Finding recipes you can make…</Text>
        </View>
      </ScrollView>
    );
  }

  // 4) Error (with nothing to show).
  if (error && recipes.length === 0) {
    return (
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <Header />
        <View style={styles.centerBox}>
          <Text style={styles.centerEmoji}>⚠️</Text>
          <Text style={styles.centerTitle}>Couldn't get recipes</Text>
          <Text style={styles.centerSub}>{error}</Text>
          <TouchableOpacity onPress={onGenerate} style={styles.retryBtn} activeOpacity={0.85}>
            <Text style={styles.retryText}>Try again</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    );
  }

  // 5) Recipes.
  const expiringIds = new Set(items.filter((i) => i.days <= 3).map((i) => i.id));
  const list = recipes.filter((r) => {
    if (filter === 'expiring') return r.uses.some((id) => expiringIds.has(id));
    if (filter === 'quick') return leadingNumber(r.time) < 20;
    if (filter === 'protein') return leadingNumber(r.nutrients.Protein || '0') >= 20;
    return true;
  });

  return (
    <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
      <Header showRefresh />

      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterRow}>
        {FILTERS.map((f) => {
          const active = filter === f.key;
          return (
            <TouchableOpacity
              key={f.label}
              onPress={() => setFilter(active ? null : f.key)}
              style={[styles.filterChip, active && styles.filterChipActive]}
              activeOpacity={0.8}
            >
              <Text style={[styles.filterChipText, active && styles.filterChipTextActive]}>{f.label}</Text>
            </TouchableOpacity>
          );
        })}
      </ScrollView>

      {loading && <Text style={styles.refreshingNote}>Refreshing suggestions…</Text>}

      {list.map((r, i) => {
        const have = r.ingredients.filter(([, has]) => has).length;
        return (
          <TouchableOpacity key={r.id} onPress={() => onOpenRecipe(r)} style={styles.card} activeOpacity={0.85}>
            <View style={[styles.cardIconWrap, { backgroundColor: TILE_BG[i % TILE_BG.length] }]}>
              <Text style={styles.cardIcon}>{r.emoji}</Text>
            </View>
            <View style={{ flex: 1, minWidth: 0 }}>
              <Text style={styles.cardName}>{r.name}</Text>
              <Text style={styles.cardMeta}>⏱ {r.time} · 🔥 {r.calories} cal · {r.servings} servings</Text>
              <View style={styles.tagRow}>
                {!!r.expiringUse && (
                  <View style={styles.expiringTag}>
                    <Text style={styles.expiringTagText}>⏰ {r.expiringUse}</Text>
                  </View>
                )}
                <View style={styles.haveTag}>
                  <Text style={styles.haveTagText}>You have {have}/{r.ingredients.length}</Text>
                </View>
              </View>
            </View>
          </TouchableOpacity>
        );
      })}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scroll: { padding: 20, paddingTop: 10, paddingBottom: 120 },
  headerRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  heading: { fontFamily: fonts.display700, fontSize: 26, letterSpacing: -0.7, color: C.text },
  subtitle: { fontSize: 13.5, color: C.muted, fontFamily: fonts.body500, marginTop: 6, lineHeight: 20 },
  refreshBtn: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  refreshIcon: { fontSize: 22, color: C.green, marginTop: -1 },
  apiCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 18, padding: 16, marginTop: 18, gap: 10 },
  apiLabel: { fontFamily: fonts.body700, fontSize: 13, color: C.muted },
  apiHint: { fontSize: 13, color: C.muted, fontFamily: fonts.body500, lineHeight: 19 },
  apiInput: { backgroundColor: C.cream, borderWidth: 1, borderColor: C.border, borderRadius: 12, paddingHorizontal: 14, height: 46, fontSize: 14, fontFamily: fonts.body400, color: C.text },
  apiSaveBtn: { backgroundColor: C.green, borderRadius: 12, height: 46, alignItems: 'center', justifyContent: 'center' },
  apiSaveText: { color: '#F4EFE3', fontFamily: fonts.body700, fontSize: 15 },
  centerBox: { alignItems: 'center', paddingHorizontal: 24, paddingTop: 70, gap: 12 },
  centerEmoji: { fontSize: 50 },
  centerTitle: { fontFamily: fonts.display700, fontSize: 20, color: C.text, textAlign: 'center' },
  centerSub: { fontSize: 14, color: C.muted, fontFamily: fonts.body500, textAlign: 'center', lineHeight: 21 },
  retryBtn: { marginTop: 8, backgroundColor: C.green, borderRadius: 14, paddingVertical: 13, paddingHorizontal: 30 },
  retryText: { color: '#F4EFE3', fontFamily: fonts.body700, fontSize: 15 },
  filterRow: { gap: 8, paddingVertical: 14 },
  filterChip: { paddingVertical: 9, paddingHorizontal: 15, borderRadius: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: C.border },
  filterChipActive: { backgroundColor: C.green, borderColor: C.green },
  filterChipText: { fontFamily: fonts.body700, fontSize: 13, color: '#5A6450' },
  filterChipTextActive: { color: '#F4EFE3' },
  refreshingNote: { fontSize: 12.5, color: C.muted, fontFamily: fonts.body600, marginBottom: 10 },
  card: { backgroundColor: '#fff', borderWidth: 1, borderColor: C.border, borderRadius: 22, padding: 14, marginBottom: 14, flexDirection: 'row', gap: 14, alignItems: 'center' },
  cardIconWrap: { width: 80, height: 80, borderRadius: 18, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  cardIcon: { fontSize: 42 },
  cardName: { fontFamily: fonts.display700, fontSize: 16.5, color: C.text, letterSpacing: -0.3 },
  cardMeta: { fontSize: 12.5, color: C.muted, fontFamily: fonts.body600, marginVertical: 5 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  expiringTag: { backgroundColor: '#FBF0D8', borderRadius: 9, paddingVertical: 4, paddingHorizontal: 9 },
  expiringTagText: { color: '#9A6713', fontFamily: fonts.body700, fontSize: 11 },
  haveTag: { backgroundColor: '#E8F2E5', borderRadius: 9, paddingVertical: 4, paddingHorizontal: 9 },
  haveTagText: { color: '#2C6B43', fontFamily: fonts.body700, fontSize: 11 },
});
